version: '3.8'

services:
  app-questie:
    image: questie-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db-questie

  db-questie:
    image: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata: